# Generated by Django 4.1.7 on 2023-05-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0004_skillrating'),
        ('accounts', '0005_user_country_user_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=20000)),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('end_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('members', models.ManyToManyField(to='accounts.developerprofile')),
                ('required_skills', models.ManyToManyField(to='skills.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
