# Generated by Django 4.1.7 on 2023-04-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('PROJECT_MANAGER', 'PROJECT_MANAGER'), ('DEVELOPER', 'DEVELOPER')], default='DEVELOPER', max_length=20),
        ),
    ]
