# Generated by Django 4.1.7 on 2023-04-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
