# Generated by Django 4.1.7 on 2023-04-18 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_developerprofile'),
        ('skills', '0004_skillrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='skills',
            field=models.ManyToManyField(through='skills.SkillRating', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='developerprofile',
            index=models.Index(fields=['availability'], name='accounts_de_availab_177235_idx'),
        ),
    ]
