# Generated by Django 4.1.7 on 2023-04-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_developerprofile_skills_developerprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='occupied',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
