# Generated by Django 4.1.7 on 2023-05-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_developerprofile_occupied'),
        ('accounts', '0005_user_country_user_profile_photo_and_more'),
    ]

    operations = [
    ]
