# Generated by Django 4.1.7 on 2023-05-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20230502_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('PROJECT MANAGER', 'PROJECT MANAGER'), ('DEVELOPER', 'DEVELOPER')], default='DEVELOPER', max_length=20),
        ),
    ]
