# Generated by Django 4.1.7 on 2023-05-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='current_project_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='current_project_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
