# Generated by Django 4.1.7 on 2023-05-11 15:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_developerprofile_current_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='employment_status',
            field=models.CharField(choices=[('INTERN', 'INTERN'), ('EMPLOYEE', 'EMPLOYEE'), ('NATIONAL SERVICE PERSONS', 'NATIONAL SERVICE PERSONS')], default='INTERN', max_length=30),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('skills_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('developer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='accounts.developerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('school_name', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('developer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='accounts.developerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
