# Generated by Django 4.1.7 on 2023-05-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_developerprofile_current_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='current_project',
            field=models.CharField(blank=True, max_length=128, verbose_name='current_project'),
        ),
    ]
