# Generated by Django 4.1.7 on 2023-05-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_developerprofile_current_project'),
        ('accounts', '0009_developerprofile_employment_status_workexperience_and_more'),
    ]

    operations = [
    ]
