# Generated by Django 4.1.7 on 2023-05-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20230512_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='job_information',
            field=models.CharField(choices=[('Associate', 'Associate'), ('Junior Associate', 'Junior Associate'), ('Senior Associate', 'Senior Associate'), ('Expert', 'Expert')], default='Associate', max_length=30),
        ),
    ]
