# Generated by Django 4.1.7 on 2023-04-18 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_developerprofile'),
        ('skills', '0003_alter_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comment', models.CharField(max_length=255)),
                ('developer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.developerprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
